resources:
    - ../base
namespace: dev-namespace

patches:
  - path: patch-replace-replicas.yaml
    target:
      kind: Deployment
      name: my-deployment
      group: apps
      version: v1
  - path: patch-add-ports.yaml
    target:
      kind: Service
      name: "*-service"
