# point to the relative path with the base yaml files
resources:
    - ../base
# change namespace, or add it if it does not exists
namespace: dev-namespace

# patches in JsonPatches6902 format
patches:
  - path: patch-replace-replicas.yaml
    target:
      kind: Deployment
      name: my-deployment
      group: apps
      version: v1
  - path: patch-add-ports.yaml
    target:
      kind: Service
      name: "*-service"
